<?php
Yii::setAlias('common', dirname(__DIR__));
Yii::setAlias('frontend', dirname(dirname(__DIR__)) . '/frontend');
Yii::setAlias('backend', dirname(dirname(__DIR__)) . '/backend');
Yii::setAlias('console', dirname(dirname(__DIR__)) . '/console');
Yii::setAlias('news', '/userfiles/news');
Yii::setAlias('blog', '/userfiles/blog');
Yii::setAlias('varieties_of_tea', '/userfiles/varieties_of_tea');
Yii::setAlias('variety_of_products', '/userfiles/variety_of_products');
Yii::setAlias('our_case', '/userfiles/our_case');
Yii::setAlias('ourclients', '/userfiles/ourclients');
Yii::setAlias('packing', '/userfiles/packing');
Yii::setAlias('boxes', '/userfiles/boxes');
Yii::setAlias('workers', '/userfiles/workers');
Yii::setAlias('actions', '/userfiles/actions');
Yii::setAlias('lte_images', '/_root/lte/img');
Yii::setAlias('gallery', '/userfiles/gallery');
Yii::setAlias('geography', '/userfiles/geography');
Yii::setAlias('catalog', '/userfiles/catalog');
Yii::setAlias('templates', dirname(dirname(__DIR__)) . '/frontend/views/site');